import Head from 'next/head'
import { connect } from "react-redux";
import { useEffect, useState } from 'react'
import Image from 'next/image'
import { GetResponse } from '~/api/endpoints/response'
import {IResponse} from '~/interfaces'
import {responseEntity} from '~/api/mockEntity'
import { IInitialState } from "~/interfaces";

const Home = (props) => {
  const {textContent} = props
   const { navbar } = textContent;
  return (
      <div className="">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className="">
 

          <div className='flex justify-center text-sm w-1/4 bg-red-500 h-5 '>
            {navbar && 
            (<h1>{navbar.menu.contact}</h1> )
            }           
            </div>
        </main>
  
        <footer className="">

        </footer>
      </div>
    )
};

const mapStateToProps = (state: IInitialState) => {
  return {
    language: state.language,
    textContent: state.textContent
  };
};

export default connect(mapStateToProps)(Home);
